name: build and deploy docs
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install sphinx
        run: sudo apt-get install -y python3-sphinx
      - name: Install project
        run: npm install
      - name: Build docs
        run: |
          mkdir -p docs/_static
          npm run build-node
          npm run build-docs
          npm run generate-icon-tokens
          cp -r public/icons docs-src/
          sphinx-build docs-src docs/
      - name: Deploy doc
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: docs
